### ISSUE TITLE
Does this works on CPU?

### ISSUE THREAD

**Issue by sainimohit23** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#105]
I tried to estimate the pose of the subjects in an image. After running the program with arguments. It seems like it is running for forever. It never gives output. I tried it on i5 6th gen CPU.

**Comment by michalfaber** [comment]
Hi @sainimohit23 demo_image.py should work on CPU. I tested it on mac.

**Comment by sainimohit23** [comment]
@michalfaber the demo .ipynb notebook is working fine but demo_image.py is not working for me. Occasionally it is crashing my system.

**Comment by michalfaber** [comment]
@sainimohit23 That would be great
