### ISSUE TITLE
PAF ordering corresponding to the limbs?

### ISSUE THREAD

**Issue by alecda573** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#139]
I am trying to figure which indexes of the out putted PAFs correspond to which limbs. Also, when reconstructing the skeleton there are only 17 connections which would correspond to 34 scalar fields instead of the 38 outputted by the network, could I please have some clarifiction to this?

**Comment by michalfaber** [comment]
Hi
Have a look at the function create_paf in label_maps.py
There is a loop over pairs of body parts:

```
for plane_idx, (j_idx1, j_idx2) in enumerate(JointsLoader.joint_pairs):
...
```

So the index of a pair in JointsLoader.joint_pairs determines the location of PAF's dx and dy in the following way:
Index of PAF's dx component = plane_idx * 2
Index of PAF's dy component = plane_idx * 2 + 1
(Note that dx and dy are stored sequentially)

Sequence of all joints are defined in this list (label_maps.py):

```
...
joint_pairs = list(zip(
        [1, 8,  9,  1, 11, 12, 1, 2, 3, 2, 1, 5, 6, 5, 1, 0, 0, 14, 15],
        [8, 9, 10, 11, 12, 13, 2, 3, 4, 16, 5, 6, 7, 17, 0, 14, 15, 16, 17]))
...

```
For example, at index 2 we have the pair: (9, 10). Next, find out what heatmaps are under those indices.
Check out the list idx_in_coco_str (training/dataflow.py):

```
...
idx_in_coco_str = [
        'Nose','Neck','RShoulder','RElbow','RWrist','LShoulder','LElbow','LWrist',
'RHip','RKnee','RAnkle','LHip','LKnee','LAnkle','REye','LEye','REar','LEar']
...

```
So, it looks like that at index 9 is RKnee and at index 10 is RAnkle.
Back to the joint_pairs. In this example plane_idx=2 so the
PAF's dx component of RKnee-RAnkle is located at 2 * 2 = 4
PAF's dy component of RKnee-RAnkle is located at 2 * 2 + 1 = 5

Hope it helps you.

**Comment by michalfaber** [comment]
Hi
Have a look at the function create_paf in label_maps.py
There is a loop over pairs of body parts:

```
for plane_idx, (j_idx1, j_idx2) in enumerate(JointsLoader.joint_pairs):
...
```

So the index of a pair in JointsLoader.joint_pairs determines the location of PAF's dx and dy in the following way:
Index of PAF's dx component = plane_idx * 2
Index of PAF's dy component = plane_idx * 2 + 1
(Note that dx and dy are stored sequentially)

Sequence of all joints are defined in this list (label_maps.py):
...
joint_pairs = list(zip(
        [1, 8,  9,  1, 11, 12, 1, 2, 3, 2, 1, 5, 6, 5, 1, 0, 0, 14, 15],
        [8, 9, 10, 11, 12, 13, 2, 3, 4, 16, 5, 6, 7, 17, 0, 14, 15, 16, 17]))
...

For example, at index 2 we have the pair: (9, 10). Next, find out what heatmaps are under those indices.
Check out the list idx_in_coco_str (training/dataflow.py):

```
...
idx_in_coco_str = [
        'Nose','Neck','RShoulder','RElbow','RWrist','LShoulder','LElbow','LWrist',
'RHip','RKnee','RAnkle','LHip','LKnee','LAnkle','REye','LEye','REar','LEar']
...


```So, it looks like that at index 9 is RKnee and at index 10 is RAnkle.
Back to the joint_pairs. In this example plane_idx=2 so the
PAF's dx component of RKnee-RAnkle is located at 2 * 2 = 4
PAF's dy component of RKnee-RAnkle is located at 2 * 2 + 1 = 5

Hope it helps you.

**Comment by michalfaber** [comment]
Hi
Have a look at the function create_paf in label_maps.py
There is a loop over pairs of body parts:

```
for plane_idx, (j_idx1, j_idx2) in enumerate(JointsLoader.joint_pairs):
...
```

So the index of a pair in JointsLoader.joint_pairs determines the location of PAF's dx and dy in the following way:
Index of PAF's dx component = plane_idx * 2
Index of PAF's dy component = plane_idx * 2 + 1
(Note that dx and dy are stored sequentially)

Sequence of all joints are defined in this list (label_maps.py):
...
joint_pairs = list(zip(
        [1, 8,  9,  1, 11, 12, 1, 2, 3, 2, 1, 5, 6, 5, 1, 0, 0, 14, 15],
        [8, 9, 10, 11, 12, 13, 2, 3, 4, 16, 5, 6, 7, 17, 0, 14, 15, 16, 17]))
...

For example, at index 2 we have the pair: (9, 10). Next, find out what heatmaps are under those indices.
Check out the list idx_in_coco_str (training/dataflow.py):

```
...
idx_in_coco_str = [
        'Nose','Neck','RShoulder','RElbow','RWrist','LShoulder','LElbow','LWrist',
'RHip','RKnee','RAnkle','LHip','LKnee','LAnkle','REye','LEye','REar','LEar']
...


```So, it looks like that at index 9 is RKnee and at index 10 is RAnkle.
Back to the joint_pairs. In this example plane_idx=2 so the
PAF's dx component of RKnee-RAnkle is located at 2 * 2 = 4
PAF's dy component of RKnee-RAnkle is located at 2 * 2 + 1 = 5

Hope it helps you.
