### ISSUE TITLE
Training with local data

### ISSUE THREAD

**Issue by DingGit** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#15]
Hi @michalfaber, thanks for the fantastic work.
I was trying to see if I can still train with local data only, without augmentation.
Apparently it says that "use_client_gen = False" is deprecated in the code, and a brief try shows that the format in locally generated h5 file is not compatible with what specified in DataIterator.
So my question is that, was there once a working version of for training with local data that you can upload, or maybe you can shed some light on how I should modify the code if I want to train with local data without augmentation? Thanks!

**Comment by michalfaber** [comment]
Hi @DingGit 
Deprecated DataIterator was used to iterate over augmented dataset file generated by rmpe_dataset_transformer tool. If you would like to train with local data without augmentation, modify this part https://github.com/michalfaber/rmpe_dataset_server/blob/555445514b287062e407989a284dd9023171dc5b/DataTransformer.cpp#L600

**Comment by DingGit** [comment]
Thanks, I'll look into that.

**Comment by DingGit** [comment]
Is it that the rmpe server not only doing data augmentation, but also calculating confidence map and PAF on the fly? @michalfaber

**Comment by michalfaber** [comment]
Yes. https://github.com/michalfaber/keras_Realtime_Multi-Person_Pose_Estimation/blob/master/training/inspect_dataset.ipynb
