### ISSUE TITLE
"Division by 0" running "demo_image.py"

### ISSUE THREAD

**Issue by elmuz** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#18]
I was testing the file _demo_image.py_ with a continuous stream of jpg files (consecutive frames read from a folder). There's a file that keeps producing the following error:

> /home/alessio/Sandbox/dev/PAF-pose-estimation/demo_image.py:109: RuntimeWarning: invalid value encountered in true_divide
>   vec = np.divide(vec, norm)
> Traceback (most recent call last):
>   File "/home/alessio/Sandbox/dev/PAF-pose-estimation/demo_image.py", line 258, in <module>
>     process(input_image, params, model_params)
>   File "/home/alessio/Sandbox/dev/PAF-pose-estimation/demo_image.py", line 123, in process
>     0.5 * oriImg.shape[0] / norm - 1, 0)
> ZeroDivisionError: float division by zero

It's strange since frames are very similar to each other, and with previous frames works ok. Here's the guilty frame.
![000004_rgb](https://user-images.githubusercontent.com/9587977/32387326-73606a76-c0c4-11e7-9330-78fc302def83.jpg)
What can be the reason for that?

**Comment by michalfaber** [comment]
@elmuz I've fixed the issue. Actually, this is a perfect failure case - left hand and left elbow overlap. Thanks.

**Comment by elmuz** [comment]
Thank you!
