### ISSUE TITLE
Can't find configobj

### ISSUE THREAD

**Issue by andrehuang** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#21]
I downloaded the zip directly and run the "demo_image.py", which returned:

> `Traceback (most recent call last):
>   File "D:/Python/keras_Realtime_Multi-Person_Pose_Estimation-master/keras_Realtime_Multi-Person_Pose_Estimation-master/demo_image.py", line 7, in <module>
>     from config_reader import config_reader
>   File "D:\Python\keras_Realtime_Multi-Person_Pose_Estimation-master\keras_Realtime_Multi-Person_Pose_Estimation-master\config_reader.py", line 1, in <module>
>     from configobj import ConfigObj
> ModuleNotFoundError: No module named 'configobj'`

**Comment by andrehuang** [comment]
Solved

**Comment by dlazares** [comment]
Got this too. Can you explain the solution?

**Comment by anatolix** [comment]
`pip install configobj`     or   `conda install configobj`
