### ISSUE TITLE
KeyError: "Unable to open object (Object 'label' doesn't exist)" of h5["label"]

### ISSUE THREAD

**Issue by binliu-base** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#22]
When I try to run the  inspect_dataset.ipynb file with the hdf5 file  val_generated_dataset.h5,  which I create with the generate_hdf5.py script.  I ran into this error.   KeyError: "Unable to open object (Object 'label' doesn't exist)"

In generate_hdf5.py,  I see there is only create one group  "dataum".  
    grp = h5.create_group("datum")

So seems the group "label" not been created when creating the val_generated_dataset.h5.  if  the  inspect_dataset.ipynb file not been updated after the code change of generate_hdf5.py ?

**Comment by anatolix** [comment]
afaik you should run inspect dataset on dataset_transformer output or dataset_server, generate_hdf5 dataset is in different format

**Comment by binliu-base** [comment]
got it, thanks!

**Comment by binliu-base** [comment]
close the issue due to not a bug.
