### ISSUE TITLE
How does it works 'mask miss' and 'mask all'

### ISSUE THREAD

**Issue by LEESEYUN** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#26]
Thank you for reading this question :)

How does the mask works in the code ?

 It just use to product mask miss * heatmap?

**Comment by piperod** [comment]
This explanation helped me yesterday, it might give you at least some notion on what it is doing. https://github.com/michalfaber/keras_Realtime_Multi-Person_Pose_Estimation/issues/8#issuecomment-342977756

**Comment by j1mehta** [comment]
Thanks @piperod. It would be great to have an FAQ maintained by everyone involved. We surely can't expect @michalfaber to answer all questions.
