### ISSUE TITLE
Error while running generate_hdf5.py

### ISSUE THREAD

**Issue by Yuren-Zhong** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#35]
While I run `python generate_hdf5.py`,
the output is : 

loading annotations into memory...
Done (t=5.35s)
creating index...
index created!
Image ID  391895
Image ID  522418
Image ID  184613
Image ID  318219
...
Image ID  407646
Image ID  220310
Image ID  512403
Image ID  168974
Image ID  552775
Image ID  394940
Image ID  15335
Num samples  55242
Traceback (most recent call last):
  File "generate_hdf5.py", line 322, in <module>
    writeHDF5()
  File "generate_hdf5.py", line 290, in writeHDF5
    img4ch = np.concatenate((img, meta_data, mask_miss[..., None], mask_all[..., None]),
TypeError: 'NoneType' object is not subscriptable

**Comment by piperod** [comment]
It happened to me once too. I wasn't creating all the masks for all the files, so when it read the mask or the image found and empty "NoneType' array. I suggest you to check that you have all the masks generated for all the files you are including in the annotations.
