### ISSUE TITLE
some troubles with demo_image.py

### ISSUE THREAD

**Issue by woxihuanchirou** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#46]
`
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--image', type=str, required=True, help='input image')
    parser.add_argument('--output', type=str, default='result.png', help='output image')
    parser.add_argument('--model', type=str, default='model/keras/model.h5', help='path to the weights file')

    args = parser.parse_args()
    input_image = args.image 
    keras_weights_file = args.model

    tic = time.time()
    print('start processing...')`

it says
"usage: demo_image.py [-h] --image IMAGE [--output OUTPUT] [--model MODEL]
demo_image.py: error: the following arguments are required: --image
An exception has occurred, use %tb to see the full traceback."

how can i deal with this problem?I'm a Chinese and my English is not good:)

**Comment by byzaagl** [comment]
hi, did you remember that how do you fix that issue? I'm also dealing with it -.-
