### ISSUE TITLE
 How to understand parameter "target_dist = 0.6"

### ISSUE THREAD

**Issue by USTClj** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#51]
What's the use of target_dist in
https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/e289c45e991b74bafe64335e33446d7570b3d284/training/setLayers.py#L458

**Comment by anatolix** [comment]
It used in picture augmentation during training. Rough meaning is "height of main person on image should be approximately 0.6 if image size". It used in this file in my code:
https://github.com/anatolix/keras_Realtime_Multi-Person_Pose_Estimation/blob/master/py_rmpe_server/py_rmpe_transformer.py
