### ISSUE TITLE
My python crash when i run generate_marks.py.

### ISSUE THREAD

**Issue by beebrain** [michalfaber/keras_Realtime_Multi-Person_Pose_Estimation#53]
I ran this project on windows platform. I sync coco data follow instruction, but when I executed  generate_marks.py. It's crash. 
How to fix that. Please suggest me.

![image](https://user-images.githubusercontent.com/10016227/35481365-b8a5005a-0454-11e8-9acf-24c53e22036e.png)

**Comment by anatolix** [comment]
1. Try to figure out which line cause the crash. It is hard to figure out the cause. 
2. in general python almost never cause crashes, but C++ could. Only c++ code it this thing is coco api, try to rebuild it, most probably crash could be because of building with  wrong python version

**Comment by beebrain** [comment]
Than you @anatolix for your suggestion.
Now I changed a C compiler version. It worked.
